### PR TITLE
Upgrade to Rails 4.1 and Mongoid 4

### PR DESCRIPTION
**Pull request by alext**
To keep up to date etc.

This will require a corresponding change to alphagov-deployment.

### CODE REVIEW

**Comment by alext** [comment]
See https://github.gds/gds/alphagov-deployment/pull/829 for deployment changes that should be merged at the same time.

**Comment by benilovj** [comment]
Why not rails 4.2?

**Comment by alext** [comment]
It's still at .0.  I was going to wait for 4.2.1 before upgrading - let others take the early-adopter pain.

**Comment by benilovj** [comment]
@alext [alright I'll tell you how it goes next week](https://github.com/alphagov/support-api/pull/23) :)

**Pull request merged**
