### PR TITLE
Update gemfile dependencies

### PR DESCRIPTION
**Pull request by cbaines**

### CODE REVIEW

**Comment by cbaines** [comment]
> Looks good. I think it still makes sense to have our own dependencies pinned to a major version (though this has all got confusing in the age of dependabot)

Thanks for taking a look :) I'm interested in your point about pinning to a major version. Since the Gemfile.lock contains a pin to an exact version, I didn't think having some version in the Gemfile was much use. Maybe for major versions of non GOV.UK gems it has some use, but at least for GOV.UK gems, I can't really see a situation where we would want to do a major update that didn't apply to all applications. What do you think?

**Comment by kevindew** [comment]
> Thanks for taking a look :) I'm interested in your point about pinning to a major version. Since the Gemfile.lock contains a pin to an exact version, I didn't think having some version in the Gemfile was much use. Maybe for major versions of non GOV.UK gems it has some use, but at least for GOV.UK gems, I can't really see a situation where we would want to do a major update that didn't apply to all applications. What do you think?

No problem. So my thoughts on it are that you should always expect `bundle update` to be a safe command to run and it'll catch all minor changes and bugfixes with a low chance of backwards compatibility issues. Whereas when there are major changes with backwards compatibility issues these require a bit more caution and thus should require a tweak to the Gemfile.

**Comment by cbaines** [comment]
> So my thoughts on it are that you should always expect bundle update to be a safe command to run and it'll catch all minor changes and bugfixes with a low chance of backwards compatibility issues. Whereas when there are major changes with backwards compatibility issues these require a bit more caution and thus should require a tweak to the Gemfile.

Ok, that makes sense to me :)

**Comment by cbaines** [comment]
I've put up a patch for adding these in to the router-api now https://github.com/alphagov/router-api/pull/140

**Comment by kevindew** [comment]
Cool thanks - just added a comment to it

**Pull request merged**
