### PR TITLE
Changes to read production config from ENV variables.

### PR DESCRIPTION
**Pull request by alext**
This will enable us to simplify the deployment process.

The corresponding puppet changes need to be merged first - https://github.gds/gds/puppet/pull/2466

### CODE REVIEW

**Comment by KushalP** [comment]
This is five months out of date.

@alext do you still want this to be reviewed/merged?

**Comment by mattbostock** [comment]
@alext Am I correct in thinking that this won't pick up [`SECRET_KEY_BASE`](https://github.gds/gds/puppet/pull/2466/files#diff-cb1ac17f2f2b3e699f7273f17ccc7244R45)?

**Comment by alext** [comment]
It will because that's what the [default `secrets.yml` does](https://github.com/alphagov/router-api/blob/master/config/secrets.yml#L22).  However, the deploy scripts are currently overwriting this at deploy time.

**Comment by mattbostock** [comment]
Thanks @alext, I'll raise a PR to fix that.

**Pull request merged**
